# Generated by Django 4.0.5 on 2022-11-14 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_city_options_city_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='date',
        ),
        migrations.AddField(
            model_name='city',
            name='datatime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 14, 17, 30, 26, 794119)),
        ),
    ]
