# Generated by Django 4.0.5 on 2022-11-14 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_remove_city_date_city_datatime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='datatime',
        ),
        migrations.AddField(
            model_name='city',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 14, 17, 59, 46, 498742)),
        ),
    ]
